[package]
name = "snake"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
fixedbitset = "0.4.2"
bincode = "2.0.0-rc.3"

[lib]
crate-type = ["lib"]
